Building DAG of jobs...
Full Traceback (most recent call last):
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 1876, in collect_potential_dependencies
    yield PotentialDependency(file, known_producers[file], True)
KeyError: '/datapool/home/fengbx/data3/test/results/test_result/read_counts/result/count.all.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/jobs.py", line 136, in new
    obj = self.cache[key]
KeyError: ('merge_counts',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/io.py", line 974, in format_match
    value = wildcards[name]
KeyError: 'sample'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/rules.py", line 909, in expand_input
    incomplete = self._apply_wildcards(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/rules.py", line 872, in _apply_wildcards
    concrete = concretize(item_, wildcards, _is_callable)
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/rules.py", line 895, in concretize_iofile
    return f.apply_wildcards(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/io.py", line 740, in apply_wildcards
    apply_wildcards(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/io.py", line 986, in apply_wildcards
    return _wildcard_regex.sub(format_match, pattern)
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/io.py", line 984, in format_match
    raise WildcardError(str(ex))
snakemake.exceptions.WildcardError: 'sample'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/__init__.py", line 792, in snakemake
    success = workflow.execute(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/workflow.py", line 895, in execute
    dag.init()
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 214, in init
    job = self.update([job], progress=progress, create_inventory=True)
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 927, in update
    raise exceptions[0]
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 885, in update
    self.update_(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 978, in update_
    for res in potential_dependencies:
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 1894, in collect_potential_dependencies
    file2jobs(file, wildcards_dict=job.wildcards_dict),
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 1985, in file2jobs
    self.new_job(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/dag.py", line 1708, in new_job
    job = self.job_factory.new(
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/jobs.py", line 138, in new
    obj = Job(rule, dag, wildcards_dict, format_wildcards, targetfile)
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/jobs.py", line 210, in __init__
    ) = self.rule.expand_input(self.wildcards_dict, groupid=groupid)
  File "/datapool/home/fengbx/mambaforge/envs/bioinfo_env/lib/python3.8/site-packages/snakemake/rules.py", line 921, in expand_input
    raise WildcardError(
snakemake.exceptions.WildcardError: Wildcards in input files cannot be determined from output files:
'sample'

WildcardError in rule merge_counts in file /datapool/home/fengbx/data3/test/scripts/snakefile, line 111:
Wildcards in input files cannot be determined from output files:
'sample'
unlocking
removed all locks
